### ISSUE TITLE
Comment on validity of claims

### ISSUE THREAD

**Issue by ngc5195bee** [microsoft/DCVC#19]
First of all, I want to congratulate you on your excellent results. 

However, I have reservations about the claim stating that your codec "is the first end-to-end neural video codec to exceed ECM using the highest compression ratio configuration, in terms of PSNR for YUV420 content".

I believe it would be more accurate to compare your codec against the established benchmarks of VTM and ECM results using JVET common test conditions. Additionally, it's crucial to include a clear disclaimer regarding the usage of a forced intra-period of 32 for ECM and VTM, as this will have affected the comparison outcomes (VTM does not need such a frequent intra-period, but I assume your model does). When testing your model, my results were close but did not beat VTM. 

By ensuring a fair and direct comparison, your findings will hold more credibility within the video coding community.

**Comment by yaohualibin** [comment]
Thank you for the comments. We've refined the description of DCVC-DC. We also released a new model DCVC-FM, which exceeds ECM low delay setting using single intra frame setting.
Please feel free to reopen it if you have further comments and suggestions.
