### ISSUE TITLE
Pretrained Model of EVC is not available.

### ISSUE THREAD

**Issue by fdap** [microsoft/DCVC#20]
Thanks for sharing your code. While the link to the pre-trained models of EVC is unavailable, may you update the download link? That will be very helpful, thx.

**Comment by ustclibin** [comment]
I just run python ./download.py in ./EVC/checkpoints/. It downloaded the models successfully. Would you please try it again?

**Comment by fdap** [comment]
I cannot get the weights after running the download script :disappointed:. I guess it's my network problem, thanks for your kind response.
