### ISSUE TITLE
`.MLCodec_rans|.MLCodec_CXX` could not be resolved.

### ISSUE THREAD

**Issue by MagicS0ng** [microsoft/DCVC#22]
Thank you for your greak work!
When I was working on the released `DCVC-HEM` code,  I found some errors saying   'Import ".MLCodec_rans"|".MLCodec_CXX"  could not be resolved' in the `entropy_models.py` file and I didn't found any clue about these two folders/files/libraries. So could you guys help me with this?
![image](https://github.com/microsoft/DCVC/assets/55200229/f40338bf-ed89-43ba-b49f-40c1847cce5d)

**Comment by ustclibin** [comment]
Please follow the following link to build the C++ code.
https://github.com/microsoft/DCVC/tree/main/DCVC-HEM#build-the-project

**Comment by MagicS0ng** [comment]
@ustclibin thanks for you helpful reply firstly. However, although I have built the C++ code following the doc,  the editor still report the error.

**Comment by ustclibin** [comment]
Did you build the C++ code successfully? Are there any binary output after building C++ code?

**Comment by MagicS0ng** [comment]
@ustclibin can not appreciate your help anymore, I found why the error occurred. Now it works.

**Comment by LiangChaoHu** [comment]
> @ustclibin can not appreciate your help anymore, I found why the error occurred. Now it works.

I have the same problem as you, although I have built the C++ code, the editor still report the error. Can you tell me how you solved it?

**Comment by MagicS0ng** [comment]
Compiling reports no error on windows, yet on my linux😢. So.. just transfer into windows🤦‍♂️

**Comment by LiangChaoHu** [comment]
@MagicS0ng It works, thank you!
