### ISSUE TITLE
The inconsistent test results of the compared methods

### ISSUE THREAD

**Issue by IrisNNN** [microsoft/DCVC#38]
Hello, I want to express my gratitude for your outstanding work. However, I have noticed that each method compared with DCVC-DC, ranging from the traditional VVC to the deep learning-based DCVC-TCM, DCVC-HEM, and CANF-VC, seems to yield test results considerably higher than those reported in the original paper for each dataset. Could you please explain the reason for this?

**Comment by yaohualibin** [comment]
Different papers may use different test conditions. Would you please check whether these papers are using exactly the same test conditions?

**Comment by IrisNNN** [comment]
Thank you very much for your reply！ I found in subsequent experiments that this difference is mainly due to the conversion of YUV to RGB using ffmpeg in other papers. The test results obtained from this conversion method will have a PSNR more than one dB lower than those obtained using BT.709 conversion, while the difference between BT.709 and BT.601 is not that significant.
Thank you very much for your reply. I found in subsequent experiments that this difference is mainly due to the conversion of YUV to RGB using ffmpeg in other papers. The test results obtained from this conversion method will have a PSNR more than one dB lower than those obtained using BT.709 conversion, while the difference between BT.709 and BT.601 is not that significant.

121O
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/DCVC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月28日(星期三) 下午3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/DCVC] The inconsistent test results of the compared methods (Issue #38)





 
Different papers may use different test conditions. Would you please check whether these papers are using exactly the same test conditions?

**Comment by yaohualibin** [comment]
Thanks for the confirmation. Please feel free to reopen this issue.
