### ISSUE TITLE
Nan value encountered  while testing DCVC-FM code

### ISSUE THREAD

**Issue by LHB116** [microsoft/DCVC#45]
Hi, thank you for sharing the repository. When I test the DCVC-FM code with HEVC Class D dataset, pytorch=2.0.0, python=3.10.13, numpy=1.26.4, nan value encountered, how to solve the problem?

Traceback (most recent call last):
  File "DCVC-FM/src/models/image_model.py", line 166, in encode
    encoded = self.forward_one_frame(x, q_index)
  File "DCVC-FM/src/models/image_model.py", line 149, in forward_one_frame
    bits_y = self.get_y_gaussian_bits(y_for_bit, scales_hat)
  File "DCVC-FM/src/models/common_model.py", line 74, in get_y_gaussian_bits
    gaussian = torch.distributions.normal.Normal(mu, sigma)
  File "/home/anaconda3/envs/dcvc-fm/lib/python3.10/site-packages/torch/distributions/normal.py", line 56, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/home/anaconda3/envs/dcvc-fm/lib/python3.10/site-packages/torch/distributions/distribution.py", line 62, in __init__
    raise ValueError(
ValueError: Expected parameter scale (Tensor of shape (1, 256, 32, 48)) of distribution Normal(loc: torch.Size([1, 256, 32, 48]), scale: torch.Size([1, 256, 32, 48])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[[[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]]]], device='cuda:0')

**Comment by labradon** [comment]
Hi, I experience a similar problem during testing as you did. Did you find a solution for this problem? My code crashes at the exact same position as yours with all nan values in the scale tensor.

**Comment by Cauliflower61** [comment]
Hello, I also encountered similar problem when training and finetuning image_model of DCVC-FM. But I can test DCVC-FM code on HEVC dataset except class F. Do you have the corresponding solution ?
