### ISSUE TITLE
R-D curve differences between DCVC-HEM and DCVC-DC papers

### ISSUE THREAD

**Issue by sybahk** [microsoft/DCVC#52]
Hi, first of all, thanks for your great work!
While looking around the repository to get R-D performances from the figures you provided, I found that reported performances of DCVC-DC and DCVC-HEM papers are really different.

I compared UVG dataset's RGB R-D curves.

Regarding DCVC-HEM's figure (https://github.com/microsoft/DCVC/blob/main/DCVC-HEM/assets/rd_curve_psnr.png),
- highest operating point of DCVC shows approximately (37dB, 0.10bpp) R-D performance,
- and DCVC-HEM shows approximately (38.5dB, 0.115bpp).  

However, regarding DCVC-DC's figure (https://github.com/microsoft/DCVC/blob/main/DCVC-DC/assets/rd_rgb_psnr.png), 
- DCVC's PSNR is higher than 38dB when it's bpp is much lower than 0.10bpp,
- and DCVC-HEM's is also higher than 40.5dB while it's bpp is about 0.09bpp.

I saw that dataset_config_example.json is same between two model's repositories, but are there any differences between two models' test conditions that I missed?

Thanks in advance!

**Comment by yaohualibin** [comment]
Yes, they are different. The main reason is that the RGB (png) source files are different. We are using BT.709 conversion matrix to generate png data to test RGB sequences in DCVC-DC. More details could be found at https://github.com/microsoft/DCVC/tree/main/DCVC-DC#rgb-content and the DCVC-DC paper.
